const Config = {
    MAX_LEVEL: 10,
    BLINK_TIME:250,
    DELAY_TIME:1000,
    GAME_TIME: 10000,
    BOARDMESSAGE_UPPING: 1000,
    BOARDMESSAGE_FALLING: 1300,
    SUBMESSAGE_FADE_IN_OUT: 2000,
    START_MESSAGE: 0,
    LOSE_MESSAGE:1,
    VICTORY_MESSAGE:2,
    START_SIMON:3,
};

export default Config;